batch_size: 256
cores: 2
cuda: 0
env_name: dual_sim_env_grasping
eval: true
exp_id: do
expl_noise: 0.1
gamma: 0.99
hidden_size: 256
learning_path: /home/baxter/pyb_ws/src/learning_logs
lr: 0.0001
ms_delay: 2
noise_clip: 0.5
noise_type: action
num_steps: 1000000
param_noise_mean: 0
param_noise_std: 0.01
policy_freq: 2
policy_noise: 0.2
replay_size: 1000000
reward_scaling: 0.02
rotation_augmentations: false
rotation_data_set_multiplier: 1
save_interval: 600
seed: 1207
start_steps: 30000
step_latency: 10
steps_every_simulation_hard_reset: 4000
tau: 0.005
test_steps: 12000
updates_after_traj: 250
updates_multiplier: 1
use_priortised_exp: false
